/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://mborewards.com',
  generateRobotsTxt: false, // robots.txt already generated by src/app/robots.ts
  changefreq: 'monthly',
  priority: 0.8,
  sitemapSize: 7000,
}
