import type { Metadata } from "next";
import PageShell from "@/components/PageShell";

export const metadata: Metadata = {
  title: "About MBO Rewards — Affiliate Commerce Infrastructure | MBO Rewards",
  description:
    "MBO Rewards builds affiliate commerce infrastructure for banks, fintechs, and digital platforms. Founded by Deepankar Chaudhary. API-first. Zero PII. Live in India, SEA, GCC & UK.",
  alternates: { canonical: "https://mborewards.com/about" },
  openGraph: {
    title: "About MBO Rewards — Affiliate Commerce Infrastructure | MBO Rewards",
    description: "MBO Rewards builds affiliate commerce infrastructure for banks, fintechs, and digital platforms. Founded by Deepankar Chaudhary. API-first. Zero PII. Live in India, SEA, GCC & UK.",
    url: "https://mborewards.com/about",
  },
};

const breadcrumb = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "MBO Rewards", item: "https://mborewards.com" },
    { "@type": "ListItem", position: 2, name: "About", item: "https://mborewards.com/about" },
  ],
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is MBO Rewards?",
      acceptedAnswer: { "@type": "Answer", text: "MBO Rewards is an affiliate commerce infrastructure API that enables banks, fintech apps, and digital platforms to integrate cashback, offers, and monetisation through a single REST API." },
    },
    {
      "@type": "Question",
      name: "How long does MBO Rewards integration take?",
      acceptedAnswer: { "@type": "Answer", text: "Integration typically takes 2–3 days from sandbox credentials to production. Full API documentation and dedicated integration support are provided." },
    },
    {
      "@type": "Question",
      name: "Does MBO Rewards store user personal data?",
      acceptedAnswer: { "@type": "Answer", text: "No. User identity is an opaque token generated by the client. MBO Rewards cannot reverse-map it. No names, emails, or device identifiers enter MBO systems." },
    },
    {
      "@type": "Question",
      name: "What is MBO Rewards pricing?",
      acceptedAnswer: { "@type": "Answer", text: "MBO Rewards has no setup fees and no monthly charges. Revenue share is earned only on confirmed affiliate conversions, agreed at onboarding." },
    },
    {
      "@type": "Question",
      name: "What markets does MBO Rewards serve?",
      acceptedAnswer: { "@type": "Answer", text: "MBO Rewards is live in India and Southeast Asia, with active pipeline in the UAE, GCC, and United Kingdom. The API is available globally." },
    },
  ],
};

export default function AboutPage() {
  return (
    <PageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      {/* Hero */}
      <section style={{ padding: "64px 32px 64px", background: "linear-gradient(160deg, #060d1f 0%, #0d1b3e 30%, #1a3070 55%, #2952a8 72%, #4a84c4 88%, #6ba8d8 100%)", position: "relative", overflow: "hidden" }}>
        <div className="gold-line" style={{ position: "absolute", top: 0, left: 0, right: 0 }} />
        <div style={{ maxWidth: 1200, margin: "0 auto", position: "relative", zIndex: 1 }}>
          <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 20 }}>About</span>
          <h1 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(28px, 3.5vw, 48px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#ffffff", lineHeight: 1.1, marginBottom: 20, maxWidth: 780 }}>
            About MBO Rewards — Building Affiliate Commerce Infrastructure for India, GCC, SEA & UK
          </h1>
          <p style={{ fontSize: 16, color: "rgba(255,255,255,0.5)", lineHeight: 1.8, maxWidth: 600 }}>
            MBO Rewards enables banks, fintechs, loyalty programs, digital platforms, and consumer applications to launch cashback, offers, and affiliate monetisation through a single API.
          </p>
          <p style={{ fontSize: 15, color: "rgba(255,255,255,0.3)", lineHeight: 1.75, maxWidth: 560, marginTop: 16 }}>
            We simplify affiliate commerce by connecting multiple affiliate supply networks into a unified infrastructure layer, allowing businesses to integrate once and access a scalable ecosystem of campaigns, tracking, and revenue opportunities.
          </p>
          <div style={{ marginTop: 28, padding: "16px 20px", borderRadius: 10, border: "1px solid rgba(168,207,240,0.15)", background: "rgba(13,27,62,0.4)", display: "inline-block" }}>
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.5)", lineHeight: 1.6, margin: 0 }}>
              MBO Rewards is not a consumer marketplace.<br />
              <span style={{ color: "rgba(255,255,255,0.7)", fontWeight: 600 }}>It is the infrastructure powering affiliate commerce behind the scenes.</span>
            </p>
          </div>
        </div>
      </section>

      {/* Why MBO Rewards Exists */}
      <section style={{ background: "#ffffff", padding: "80px 32px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 80 }}>
          <div>
            <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>Why it exists</span>
            <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 30px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 20, lineHeight: 1.15 }}>Affiliate commerce has become one of the largest performance-driven revenue channels. The infrastructure does not.</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85 }}>
                The economics work. What does not work is the infrastructure behind it.
              </p>
              <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85 }}>
                Today, businesses must manage multiple affiliate network integrations, fragmented tracking systems, inconsistent reporting standards, and operationally heavy reconciliation processes. Every new network requires additional development effort. Every new partner introduces complexity. Every new distribution channel creates maintenance overhead.
              </p>
              <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85 }}>
                As digital products evolve toward mobile-first experiences, embedded finance, loyalty ecosystems, and AI-powered commerce, the infrastructure supporting affiliate monetisation has struggled to keep pace.
              </p>
              <p style={{ fontSize: 15, color: "#0d1b3e", fontWeight: 600, lineHeight: 1.85 }}>
                MBO Rewards was built to solve this problem.
              </p>
            </div>
          </div>

          {/* What We Do */}
          <div>
            <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>What we do</span>
            <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 30px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 16, lineHeight: 1.15 }}>One API. Unified tracking. Scalable monetisation.</h2>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.8, marginBottom: 24 }}>
              MBO Rewards acts as the infrastructure layer between affiliate supply networks and digital platforms. Through a single integration, partners gain access to:
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {[
                "Unified affiliate campaign catalog",
                "Real-time conversion tracking",
                "Commission and revenue reporting",
                "Automated campaign synchronization",
                "Dedicated tracking environments",
                "White-label deployment",
                "Developer-friendly REST APIs",
              ].map(pt => (
                <div key={pt} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", border: "1px solid #edf0f7", borderRadius: 8, background: "#fafbff" }}>
                  <div style={{ width: 5, height: 5, borderRadius: "50%", background: "linear-gradient(135deg, #e8c55a, #c9a227)", flexShrink: 0 }} />
                  <span style={{ fontSize: 14, color: "#475569" }}>{pt}</span>
                </div>
              ))}
            </div>
            <p style={{ fontSize: 14, color: "#64748b", lineHeight: 1.75, marginTop: 20 }}>
              Instead of managing multiple network relationships and integrations, businesses integrate once and unlock a scalable affiliate commerce ecosystem.
            </p>
            <div style={{ marginTop: 24, display: "flex", gap: 20 }}>
              <a href="/product" style={{ fontSize: 13, fontWeight: 600, color: "#c9a227", textDecoration: "none" }}>See the full product →</a>
              <a href="/use-cases" style={{ fontSize: 13, fontWeight: 600, color: "#64748b", textDecoration: "none" }}>Explore use cases →</a>
            </div>
          </div>
        </div>
      </section>

      {/* Why MBO Rewards — 4 pillars */}
      <section style={{ background: "#f8f9fc", padding: "72px 32px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto" }}>
          <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>Why MBO Rewards</span>
          <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 32px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 40 }}>Built differently, from the ground up.</h2>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
            {[
              { title: "One Integration", body: "Access multiple affiliate supply networks through a single API. One contract. One dashboard. One integration team." },
              { title: "White-Label First", body: "Your customers interact with your brand. MBO Rewards operates entirely in the background — invisible to your end users." },
              { title: "Built for Modern Platforms", body: "Designed for banks, fintechs, loyalty programs, digital wallets, communities, and consumer applications — not coupon sites." },
              { title: "API-First Infrastructure", body: "Built for reliability, scalability, and long-term growth. Every feature is accessible via REST API. No custom dashboards required to integrate." },
            ].map(v => (
              <div key={v.title} style={{ padding: "28px 26px", borderRadius: 14, border: "1px solid #edf0f7", background: "#ffffff" }}>
                <h3 style={{ fontFamily: "var(--font-jakarta)", fontSize: 16, fontWeight: 800, color: "#0d1b3e", marginBottom: 10 }}>{v.title}</h3>
                <p style={{ fontSize: 14, color: "#64748b", lineHeight: 1.75 }}>{v.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Founder */}
      <section style={{ background: "#ffffff", padding: "72px 32px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 80 }}>
          <div>
            <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>Founder</span>
            <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 30px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 20, lineHeight: 1.15 }}>Built from real-world execution, not theory.</h2>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85, marginBottom: 16 }}>
              MBO Rewards was founded by <strong style={{ color: "#0d1b3e" }}>Deepankar Chaudhary</strong> — a growth and commerce systems builder with experience across affiliate ecosystems, partnerships, customer acquisition, and monetisation infrastructure in India and GCC markets.
            </p>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85, marginBottom: 16 }}>
              Working closely with affiliate networks, commerce platforms, and digital growth ecosystems exposed a recurring challenge: while affiliate commerce had matured into a proven monetisation channel, the infrastructure powering it remained fragmented, difficult to integrate, and inefficient to scale.
            </p>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85, marginBottom: 28 }}>
              MBO Rewards was created to solve this problem by building a unified infrastructure layer that connects affiliate supply, tracking, attribution, and monetisation into a single platform.
            </p>
            <blockquote style={{ margin: 0, padding: "20px 24px", borderLeft: "3px solid #c9a227", background: "#faf8f0", borderRadius: "0 8px 8px 0" }}>
              <p style={{ fontSize: 15, color: "#0d1b3e", fontStyle: "italic", lineHeight: 1.7, margin: 0 }}>
                "Growth is no longer driven by channels alone. It is driven by infrastructure, distribution, and connected systems."
              </p>
            </blockquote>
          </div>

          {/* MBO Group */}
          <div>
            <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>MBO Group</span>
            <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 30px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 16, lineHeight: 1.15 }}>An ecosystem of growth, distribution, and infrastructure.</h2>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.8, marginBottom: 28 }}>
              MBO Rewards is part of MBO Group — a growth and commerce infrastructure ecosystem focused on helping modern businesses acquire users, distribute products, and monetise audiences.
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {[
                { name: "MBO Rewards", desc: "Affiliate commerce infrastructure and monetisation APIs." },
                { name: "Marketing Blue Ocean (MBO)", desc: "Growth systems, customer acquisition, and distribution solutions." },
                { name: "Corewave", desc: "Technology infrastructure, integrations, automation, and scalable platform development." },
              ].map(entity => (
                <div key={entity.name} style={{ padding: "20px 22px", borderRadius: 12, border: "1px solid #edf0f7" }}>
                  <p style={{ fontFamily: "var(--font-jakarta)", fontSize: 14, fontWeight: 700, color: "#0d1b3e", marginBottom: 6 }}>{entity.name}</p>
                  <p style={{ fontSize: 13, color: "#64748b", lineHeight: 1.65 }}>{entity.desc}</p>
                </div>
              ))}
            </div>
            <p style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.7, marginTop: 20 }}>
              Together, these businesses support a common mission: building the infrastructure that powers sustainable digital growth.
            </p>
          </div>
        </div>
      </section>

      {/* Market Opportunity */}
      <section style={{ background: "#f8f9fc", padding: "72px 32px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto" }}>
          <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>Market opportunity</span>
          <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 32px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 20 }}>The model is globally validated. The infrastructure gap in India, GCC, SEA & UK is not yet closed.</h2>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 40 }}>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85 }}>
              The affiliate commerce infrastructure category has already demonstrated strong global demand. Banks, fintech platforms, loyalty programs, and digital products are increasingly seeking monetisation channels that are measurable, scalable, and performance-driven.
            </p>
            <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85 }}>
              While mature markets have seen the emergence of dedicated affiliate infrastructure providers serving banks and fintechs at scale, India, the GCC, Southeast Asia, and the United Kingdom remain underserved by API-first, white-label solutions. MBO Rewards is building for this opportunity across all four markets.
            </p>
          </div>
          <div style={{ marginTop: 40, display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 16 }}>
            {[
              { region: "India", status: "Live" },
              { region: "Southeast Asia", status: "Live" },
              { region: "UAE / GCC", status: "Active pipeline" },
              { region: "United Kingdom", status: "Planned" },
              { region: "Global API", status: "Available" },
            ].map(m => (
              <div key={m.region} style={{ padding: "24px 20px", borderRadius: 12, border: "1px solid #edf0f7", background: "#ffffff" }}>
                <p style={{ fontFamily: "var(--font-jakarta)", fontSize: 14, fontWeight: 700, color: "#0d1b3e", marginBottom: 6 }}>{m.region}</p>
                <p style={{ fontSize: 11, color: "#94a3b8", fontWeight: 500, letterSpacing: "0.04em" }}>{m.status}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Get Started CTA */}
      <section style={{ background: "linear-gradient(160deg, #060d1f 0%, #0d1b3e 40%, #1a3070 65%, #2952a8 82%, #4a84c4 100%)", padding: "72px 32px", position: "relative" }}>
        <div className="gold-line" style={{ position: "absolute", top: 0, left: 0, right: 0 }} />
        <div style={{ maxWidth: 720, margin: "0 auto", textAlign: "center", position: "relative", zIndex: 1 }}>
          <p style={{ fontSize: 11, fontWeight: 700, color: "rgba(201,162,39,0.5)", letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 20 }}>Get started</p>
          <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 34px)", fontWeight: 800, color: "#ffffff", letterSpacing: "-0.025em", lineHeight: 1.2, marginBottom: 20 }}>
            If your platform should be monetising affiliate commerce, the infrastructure is ready.
          </h2>
          <p style={{ fontSize: 15, color: "rgba(255,255,255,0.4)", lineHeight: 1.7, marginBottom: 16 }}>
            Whether you're a fintech platform, loyalty program, digital wallet, community platform, or consumer application — MBO Rewards helps you launch affiliate commerce capabilities through a single integration.
          </p>
          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.3)", marginBottom: 36 }}>Integration takes 2–3 days. No monthly fee to get started.</p>
          <div style={{ display: "flex", gap: 16, justifyContent: "center", flexWrap: "wrap" }}>
            <a href="/contact" style={{ display: "inline-flex", fontFamily: "var(--font-jakarta)", fontSize: 13, fontWeight: 700, padding: "12px 28px", borderRadius: 8, background: "linear-gradient(135deg, #e8c55a 0%, #c9a227 100%)", color: "#0d1b3e", textDecoration: "none" }}>Get API Access</a>
            <a href="/product" style={{ display: "inline-flex", fontFamily: "var(--font-jakarta)", fontSize: 13, fontWeight: 600, padding: "12px 28px", borderRadius: 8, border: "1px solid rgba(168,207,240,0.2)", color: "rgba(255,255,255,0.7)", textDecoration: "none" }}>See the product →</a>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
