"use client";
const controls = [
  { title: "Zero PII storage", body: "MBO never receives or stores personally identifiable information. User identity is an opaque token generated by your system — we cannot reverse-map it." },
  { title: "Tenant data isolation", body: "Click, conversion, and commission data is partitioned at the data layer. No cross-contamination between clients — enforced by design, not policy." },
  { title: "RBI-aligned data residency", body: "All data is stored and processed within India on infrastructure that meets RBI guidelines on data localisation for regulated financial institutions." },
  { title: "Immutable audit logs", body: "Every API call, click, conversion, and commission is written to an append-only audit log. Available for export for compliance and internal audit teams." },
  { title: "TLS 1.3 + AES-256 at rest", body: "All traffic is encrypted in transit and at rest. API keys are hashed server-side — the plaintext is shown exactly once, at generation." },
  { title: "White-label isolation", body: "MBO branding never appears in your user-facing product. No MBO domains, pixels, or attribution data visible to your end users." },
];

export default function Security() {
  return (
    <section id="security" style={{ background: "#ffffff", padding: "120px 32px" }}>
      <div style={{ maxWidth: 1200, margin: "0 auto" }}>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 80, alignItems: "start" }}>
          {/* Left */}
          <div style={{ position: "sticky", top: 120 }}>
            <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>Security & Compliance</span>
            <h2
              style={{
                fontFamily: "var(--font-jakarta)",
                fontSize: "clamp(28px, 3vw, 42px)",
                fontWeight: 800,
                letterSpacing: "-0.025em",
                color: "#0d1b3e",
                lineHeight: 1.1,
                marginBottom: 20,
              }}
            >
              Built to pass your CISO's review.
            </h2>
            <p style={{ fontSize: 15, color: "#64748b", lineHeight: 1.7, maxWidth: 380 }}>
              Enterprise security and data governance requirements shaped every architectural
              decision — not retrofitted later. Banks and regulated platforms onboard without a
              security exception.
            </p>
          </div>

          {/* Right — controls */}
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {controls.map((c, i) => (
              <div
                key={c.title}
                style={{
                  padding: "28px 0",
                  borderBottom: i < controls.length - 1 ? "1px solid #f0f4fa" : "none",
                  display: "grid",
                  gridTemplateColumns: "20px 1fr",
                  gap: 20,
                  alignItems: "start",
                }}
              >
                <div
                  style={{
                    width: 6,
                    height: 6,
                    borderRadius: "50%",
                    background: "linear-gradient(135deg, #e8c55a, #c9a227)",
                    marginTop: 7,
                    flexShrink: 0,
                  }}
                />
                <div>
                  <p style={{ fontFamily: "var(--font-jakarta)", fontWeight: 700, fontSize: 15, color: "#0d1b3e", marginBottom: 6 }}>{c.title}</p>
                  <p style={{ fontSize: 13.5, color: "#64748b", lineHeight: 1.65 }}>{c.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
