import type { Metadata } from "next";
import PageShell from "@/components/PageShell";

export const metadata: Metadata = {
  title: "Affiliate API for Banking & Fintech Apps | MBO Rewards",
  description:
    "MBO Rewards powers affiliate commerce for banking apps, fintech platforms, loyalty programs, and digital products across India, Southeast Asia, GCC, and the United Kingdom.",
  alternates: { canonical: "https://mborewards.com/use-cases" },
  openGraph: {
    title: "Affiliate API for Banking & Fintech Apps | MBO Rewards",
    description: "MBO Rewards powers affiliate commerce for banking apps, fintech platforms, loyalty programs, and digital products across India, Southeast Asia, GCC, and the United Kingdom.",
    url: "https://mborewards.com/use-cases",
  },
};

const breadcrumb = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "MBO Rewards", item: "https://mborewards.com" },
    { "@type": "ListItem", position: 2, name: "Use Cases", item: "https://mborewards.com/use-cases" },
  ],
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is MBO Rewards?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "MBO Rewards is an affiliate commerce infrastructure API that enables banks, fintech apps, and digital platforms to integrate cashback, offers, and monetisation through a single REST API.",
      },
    },
    {
      "@type": "Question",
      name: "How long does MBO Rewards integration take?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Integration typically takes 2–3 days from sandbox credentials to production. Full API documentation and dedicated integration support are provided.",
      },
    },
    {
      "@type": "Question",
      name: "Does MBO Rewards store user personal data?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. User identity is an opaque token generated by the client. MBO Rewards cannot reverse-map it. No names, emails, or device identifiers enter MBO systems.",
      },
    },
    {
      "@type": "Question",
      name: "What is MBO Rewards pricing?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "MBO Rewards has no setup fees and no monthly charges. Revenue share is earned only on confirmed affiliate conversions, agreed at onboarding.",
      },
    },
    {
      "@type": "Question",
      name: "What markets does MBO Rewards serve?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "MBO Rewards is live in India and Southeast Asia, with active pipeline in the UAE, GCC, and United Kingdom. The API is available globally.",
      },
    },
  ],
};

const cases = [
  {
    category: "Banking Applications",
    tag: "Engagement + Revenue",
    body: "A retail bank with 2 million active users has the highest-intent, most-trusted consumer relationship in financial services. But affiliate commerce was never built for authenticated apps. Cookie tracking fails inside mobile banking environments, and building a rewards product from scratch takes years. MBO Rewards changes this. Your banking app calls the MBO API to fetch a ranked list of cashback offers — travel, e-commerce, food delivery, utilities. Users browse and activate inside your app. When a user completes a qualifying purchase, attribution is confirmed via server-side postback. You earn affiliate commission on every confirmed conversion. Zero compliance risk. Zero PII. Zero new product build.",
    link: { href: "/security", label: "How we handle security for regulated banks →" },
  },
  {
    category: "Fintech Platforms",
    tag: "Monetisation",
    body: "Fintech platforms — lending apps, payment wallets, investment platforms — sit at the moment of financial intent. A user transferring money, checking their balance, or reviewing spending is precisely the context in which a relevant merchant offer converts. MBO Rewards enables monetisation at this moment without requiring a separate rewards product. Integrate once, display offers contextually, and earn commission on confirmed purchases. The API is white-label — your users never see MBO. Your platform, your brand, your revenue.",
    link: { href: "/product", label: "See the full product architecture →" },
  },
  {
    category: "Digital Platforms",
    tag: "Incremental Revenue",
    body: "OTT platforms, news apps, EdTech products, and subscription services share a common challenge: high user engagement with limited direct monetisation paths. Advertising degrades UX. Subscriptions plateau. MBO Rewards introduces a third revenue stream — affiliate commerce — that earns incrementally from existing user behaviour without adding friction. A streaming app can show an e-commerce offer in the post-play screen. An EdTech platform can surface a stationery or course-tool offer inside a learning module. The API handles campaign fetch, tracking, and commission attribution.",
    link: { href: "/how-it-works", label: "See how integration works →" },
  },
  {
    category: "Loyalty Platforms",
    tag: "Catalog Expansion",
    body: "Loyalty operators running points, miles, or cashback programs typically maintain bilateral relationships with each merchant — separate contracts, separate tracking, separate reporting. This limits catalog size and slows expansion. MBO Rewards replaces this complexity with a single API integration that delivers 500+ campaigns across every major affiliate network, already normalised, ranked, and tracked. Your existing loyalty engine continues to work as-is. MBO Rewards adds depth to your offer catalog without adding operational overhead.",
    link: { href: "/contact", label: "Talk to us about loyalty integration →" },
  },
];

const faqs = [
  {
    q: "What types of platforms can integrate MBO Rewards?",
    a: "Any platform with an authenticated user base — banking apps, fintech wallets, digital products, loyalty programs, OTT platforms, and subscription services. If your users are logged in, MBO Rewards can generate affiliate revenue from their existing behaviour.",
  },
  {
    q: "Does MBO Rewards work in mobile apps?",
    a: "Yes. MBO Rewards uses server-side attribution with no cookies or client-side scripts, making it specifically suited for mobile environments where browser-based tracking fails — including iOS 17+, in-app browsers, and regulated financial apps.",
  },
  {
    q: "How many campaigns are available?",
    a: "500+ live campaigns across travel, e-commerce, food delivery, finance, lifestyle, and utilities. Campaigns are always ranked by conversion likelihood for your specific user segment.",
  },
  {
    q: "Is MBO Rewards visible to our users?",
    a: "No. MBO Rewards is fully white-label. Offers appear under your brand and your UX. Users never see MBO Rewards.",
  },
];

export default function UseCasesPage() {
  return (
    <PageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <section style={{ padding: "64px 32px 64px", background: "linear-gradient(160deg, #060d1f 0%, #0d1b3e 30%, #1a3070 55%, #2952a8 72%, #4a84c4 88%, #6ba8d8 100%)", position: "relative", overflow: "hidden" }}>
        <div className="gold-line" style={{ position: "absolute", top: 0, left: 0, right: 0 }} />
        <div style={{ maxWidth: 1200, margin: "0 auto", position: "relative", zIndex: 1 }}>
          <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 20 }}>Use cases</span>
          <h1 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(30px, 4vw, 52px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#ffffff", lineHeight: 1.08, marginBottom: 20, maxWidth: 720 }}>
            Use Cases — Affiliate Commerce for Banking, Fintech & Digital Platforms
          </h1>
          <p style={{ fontSize: 16, color: "rgba(255,255,255,0.4)", lineHeight: 1.7, maxWidth: 500 }}>
            Designed for platforms with an active authenticated user base. One API. Every campaign. Full server-side tracking.
          </p>
        </div>
      </section>

      <section style={{ background: "#ffffff", padding: "80px 32px" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", display: "flex", flexDirection: "column", gap: 0 }}>
          {cases.map((c, i) => (
            <div key={c.category} style={{ display: "grid", gridTemplateColumns: "280px 1fr", gap: 64, padding: "56px 0", borderBottom: i < cases.length - 1 ? "1px solid #f0f4fa" : "none", alignItems: "start" }}>
              <div>
                <p style={{ fontSize: 10, fontWeight: 700, color: "#c9a227", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 12 }}>{c.tag}</p>
                <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(20px, 2vw, 26px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.02em", lineHeight: 1.2, marginBottom: 20 }}>{c.category}</h2>
                <a href="/contact" style={{ display: "inline-flex", fontFamily: "var(--font-jakarta)", fontSize: 12, fontWeight: 700, padding: "9px 18px", borderRadius: 7, background: "linear-gradient(135deg, #e8c55a 0%, #c9a227 100%)", color: "#0d1b3e", textDecoration: "none" }}>
                  Get API Access
                </a>
              </div>
              <div>
                <p style={{ fontSize: 15, color: "#475569", lineHeight: 1.85, marginBottom: 20 }}>{c.body}</p>
                <a href={c.link.href} style={{ fontSize: 13, fontWeight: 600, color: "#c9a227", textDecoration: "none" }}>{c.link.label}</a>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ section */}
      <section style={{ background: "#f8f9fc", padding: "72px 32px" }}>
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          <span className="section-label" style={{ color: "#c9a227", display: "block", marginBottom: 16 }}>FAQ</span>
          <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 30px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 40 }}>Frequently asked questions</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {faqs.map((faq, i) => (
              <div key={faq.q} style={{ padding: "28px 0", borderBottom: i < faqs.length - 1 ? "1px solid #edf0f7" : "none" }}>
                <h3 style={{ fontFamily: "var(--font-jakarta)", fontSize: 15, fontWeight: 700, color: "#0d1b3e", marginBottom: 10 }}>{faq.q}</h3>
                <p style={{ fontSize: 14, color: "#64748b", lineHeight: 1.75 }}>{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section style={{ background: "#ffffff", padding: "64px 32px" }}>
        <div style={{ maxWidth: 600, margin: "0 auto", textAlign: "center" }}>
          <h2 style={{ fontFamily: "var(--font-jakarta)", fontSize: "clamp(22px, 2.5vw, 32px)", fontWeight: 800, color: "#0d1b3e", letterSpacing: "-0.025em", marginBottom: 14 }}>Don't see your use case?</h2>
          <p style={{ fontSize: 15, color: "#64748b", lineHeight: 1.7, marginBottom: 28 }}>If you have authenticated users, we likely have a path to affiliate revenue. Tell us about your platform.</p>
          <a href="/contact" style={{ display: "inline-flex", fontFamily: "var(--font-jakarta)", fontSize: 13, fontWeight: 700, padding: "12px 28px", borderRadius: 8, background: "linear-gradient(135deg, #e8c55a 0%, #c9a227 100%)", color: "#0d1b3e", textDecoration: "none" }}>Get API Access</a>
        </div>
      </section>
    </PageShell>
  );
}
